- name: configuring tomacat
  hosts: all
  tasks:
    - name: installing tomcat9
      apt:
        name: tomcat9
        state: present
        update_cache: yes
    - name: installing tomcat9-admin
      apt:
        name: tomcat9-admin
        state: present
    - name: copy tomcat-user.xml
      copy:
        src: /home/ubuntu/tomcat-users.xml
        dest: /etc/tomcat9
    - name: change port
      replace:
        regexp: 8080
        replace: 9090
        path: /etc/tomcat9/server.xml
    - name: restart tomcat
      service:
        name: tomcat9
        state: restarted
    - name: pause for 1 minute
      pause:
        minutes: 1
    - name: check tomcat responce on server1
      uri:
        url: http://172.31.16.159:9090
        status_code: 200
    - name: check tomcat responce on server2
      uri:
        url: http://172.31.20.198:9090
        status_code: 200
